apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-my-microservice
  labels:
    app: {{ .Release.Name }}-my-microservice
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: 30081
  selector:
    app: {{ .Release.Name }}-my-microservice